import { Inter } from "next/font/google";
import "./globals.css";

import styles from "./layout.module.css";

import Header from "./Components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Header />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
